server:
  port: 8090

#echo:
#      path: /es/**
#      url: http://localhost:9200
#      stripPrefix: true

zuul:
  ignoredServices: '*'
  prefix:
  routes:
    api:
      path: /api/room/**
      serviceId: tolucaserver
      strip-prefix: false
    auth:
      path: /auth/**
      serviceId: tolucaserver
      strip-prefix: false

endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

